<a href="https://colab.research.google.com/github/ava2467/ml-ai/blob/day-2/day_2_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]


In [ ]:
sum1=list1+list2

In [ ]:
sum1

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
sum_1=[]

In [ ]:
for  num1,num2, in zip(list1,list2):
  sum_1.append(num1+num2)


In [ ]:
sum_1

[6, 8, 10, 12]

In [ ]:
import numpy as np

In [ ]:
arr1=np.array(list1)



In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
arr2=np.array(list2)

arr2

array([5, 6, 7, 8])

In [ ]:
sum_l1=arr1+arr2
sum_l1

array([ 6,  8, 10, 12])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.ndim

1

In [ ]:
list3=[[2,3,4],[5,6,8]]

In [ ]:
arr3=np.array(list3)

In [ ]:
arr4=np.array(7)

arr4 


array(7)

In [ ]:
arr5=arr4.reshape(2,3)

ValueError: ignored